version: "3"

services:
    z-school-users:
        image: mzitouni/z-school-users:0.0.5.RELEASE
        ports:
            - "8081:8081"
        restart: always
        networks:
            - z-school-users-administration-network
        #deploy:
         #   replicas: 2

    z-school-administration:
        image: mzitouni/z-school-administration:0.0.3.RELEASE
        ports:
            - "8083:8083"
        restart: always
        depends_on:
            - z-school-users
        networks:
            - z-school-users-administration-network
            
    z-school-library:
        image: mzitouni/z-school-library:0.0.5.RELEASE
        ports:
            - "8082:8082"
        restart: always
    
    z-school-app:
        image: mzitouni/z-school-app:0.0.5.RELEASE
        ports:
            - "8080:8080"
        restart: always
        depends_on:
            - z-school-users
            - z-school-library
            - z-school-administration

networks:
    z-school-users-administration-network: